In [2]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from simpleNet import simpleNet
from gradient import numerical_gradient
from twolayer_net import TwoLayerNet

In [2]:
net = simpleNet()
print(net.W)

[[0.45098523 1.18475268 1.07364814]
 [0.99479258 0.29279671 0.53395728]]


In [3]:
x = np.array([0.6, 0.9])
p = net.predict(x)

print(p)
print(np.argmax(p))

[1.16590446 0.97436865 1.12475044]
0


In [4]:
t = np.array([0,1,1]) # 정답 레이블
net.loss(x,t)

1.2159166821880603

In [5]:
# 신경망 기울기
f = lambda w: net.loss(x,t)
dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.21541106 -0.42213703  0.20672597]
 [ 0.32311659 -0.63320554  0.31008895]]


In [6]:
# 람다를 통한 표현
f = lambda w: net.loss(x, t)
dW = numerical_gradient(f, net.W)

# 학습 알고리즘 구현하기

## 2층 신경망 클래스 구현하기

In [4]:
# params 변수
net = TwoLayerNet(input_size=784, hidden_size=100, output_size=10)
print(net.params['W1'].shape)
print(net.params['b1'].shape)
print(net.params['W2'].shape)
print(net.params['b2'].shape)

(784, 100)
(100,)
(100, 10)
(10,)


In [7]:
# 예측
x = np.random.randn(100, 784)
y = net.predict(x)

In [8]:
# grads 변수
x = np.random.randn(100, 784)
t = np.random.randn(100, 10)

grads = net.numerical_gradient(x, t) # 기울기 계산

print(grads['W1'].shape)
print(grads['b1'].shape)
print(grads['W2'].shape)
print(grads['b2'].shape)

(784, 100)
(100,)
(100, 10)
(10,)
